name: React CI/CD Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Deploy on EC2
        uses: appleboy/ssh-action@v0.1.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          script: |
            cd /home/ubuntu
            rm -rf mwpf_portfolio
            git clone https://github.com/YOUR_GITHUB_USERNAME/YOUR_REPO_NAME.git mwpf_portfolio
            cd mwpf_portfolio
            docker stop react-app || true
            docker rm react-app || true
            docker build -t react-app .
            docker run -d -p 80:80 --name react-app react-app